### ISSUE TITLE
Question: how does envoy know to query "/edsservice" route?

### ISSUE THREAD

**Issue by grayaii** [salrashid123/envoy_discovery#4]
I see that in the eds_server a route called "/edsservice" is defined:
https://github.com/salrashid123/envoy_discovery/blob/master/eds_server/main.py#L145

But how does envoy know to query that endpoint for "myservice"?
I don't see "edsservice" reference anywhere (neither in the source code of envoy, nor in this repo).

**Comment by guanw** [comment]
@grayaii I think how it works is envoy only needs to query `/v1/registration/<string:service_name>` and `/v2/discovery:endpoints`. The edsservice endpoints were implemented to update service/host information by implementers.

**Comment by salrashid123** [comment]
@guanw ...yeah, each upstream service 'registers' itself w/ the EDS service (the regsitration thing i just implemented as a Flask-RestPlus endpoint).  Envoy queries the EDS service on the `/v2/discovery:endpoints` api to find out whats been registered
- https://github.com/salrashid123/envoy_discovery/blob/master/eds_server/main.py#L88
