### ISSUE TITLE
Some improvement on your Blog

### ISSUE THREAD

**Issue by guanw** [salrashid123/envoy_discovery#5]
Hi, Just want to say this repo is really helpful for me to get started. And regarding the healthcheck issue you saw in blog, I think you can set `drain_connections_on_host_removal` to true and it should resolve.

**Comment by salrashid123** [comment]
Thanks.  I added that into the .yaml file as well as the halthcheck for the upstream service:
 https://github.com/salrashid123/envoy_discovery/commit/14341313ee313bb3eaaa06cab5e46721dc3a0259


if you're interested, here are a couple more experiments/hellow world apps for envoy:
  - https://github.com/salrashid123?utf8=%E2%9C%93&tab=repositories&q=envoy
