### ISSUE TITLE
Not an issue, just saying thanks

### ISSUE THREAD

**Issue by ghost** [salrashid123/envoy_discovery#6]
Thank you for making the envoy_discovery project open source! I stumbled upon it while I was trying to get my own EDS server to work and it was hugely helpful!

**Comment by salrashid123** [comment]
glad its helpful!.  may also be interested in the full envoy xDS, the external processor and if grpc is your thing, loadbalancing that with xds (not envoy)

https://github.com/salrashid123/envoy_control
https://github.com/salrashid123/envoy_ext_proc
https://github.com/salrashid123/grpc_xds
