### ISSUE TITLE
OnStreamResponse is not getting called

### ISSUE THREAD

**Issue by shivamnarula** [salrashid123/envoy_discovery#8]
EDS Server is not informing Envoy about the endpoints being discovered.
Tested both locally and on GKE clusters.

Can you please take a look and make necessary changes?

**Comment by salrashid123** [comment]
its there, you just need to wait for each 60s [snapshot interval(https://github.com/salrashid123/envoy_discovery/blob/master/eds_server/grpc_server.go#L277)

**Comment by shivamnarula** [comment]
I have waited for 3-4 hours, it didn't call.
Sample log

time="2023-05-05T12:25:32Z" level=info msg="Starting control plane"
time="2023-05-05T12:25:32Z" level=info msg="management server listening" port=8080
time="2023-05-05T12:26:43Z" level=info msg="OnStreamOpen 1 open for type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment"
time="2023-05-05T12:26:43Z" level=info msg="OnStreamRequest type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment"
time="2023-05-05T12:26:43Z" level=info msg="OnStreamRequest ResourceNames [some_service]"
time="2023-05-05T12:26:43Z" level=info msg="[]"
time="2023-05-05T12:26:43Z" level=info msg=">>>>>>>>>>>>>>>>>>> creating snapshot Version 1"
time="2023-05-05T12:27:43Z" level=info msg=">>>>>>>>>>>>>>>>>>> creating cluster, remoteHost, nodeID mynode,  100.96.17.9:8080, myid"
time="2023-05-05T12:27:43Z" level=info msg="[lb_endpoints:{endpoint:{address:{socket_address:{address:\"100.96.17.9\" port_value:8080}}}}]"
time="2023-05-05T12:27:43Z" level=info msg=">>>>>>>>>>>>>>>>>>> creating snapshot Version 2"
time="2023-05-05T12:28:43Z" level=info msg=">>>>>>>>>>>>>>>>>>> creating cluster, remoteHost, nodeID mynode,  100.96.17.9:8080, myid"
time="2023-05-05T12:28:43Z" level=info msg="[lb_endpoints:{endpoint:{address:{socket_address:{address:\"100.96.17.9\" port_value:8080}}}}]"
time="2023-05-05T12:28:43Z" level=info msg=">>>>>>>>>>>>>>>>>>> creating snapshot Version 3"

**Comment by salrashid123** [comment]
```
envoy  version: 624a7ac73f53f8c08f002ba10969603b2eaf7547/1.25.0-dev/Clean/RELEASE/BoringSSL
```

```log
$ go run grpc_server.go 
INFO[0000] Starting control plane                       
INFO[0000] management server listening                   port=8080
INFO[0013] OnStreamOpen 1 open for type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment 
INFO[0013] OnStreamRequest type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment 
INFO[0013] OnStreamRequest ResourceNames [myservice]    
INFO[0013] []                                           
INFO[0013] >>>>>>>>>>>>>>>>>>> creating snapshot Version 1 
INFO[0013] OnStreamResponse...                           <<<<<<<<<<<<<<<<<<<<<<<<<<<<
INFO[0013] cb.Report()  callbacks                        fetches=0 requests=1
INFO[0013] OnStreamRequest type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment 
INFO[0013] OnStreamRequest ResourceNames [myservice]    
INFO[0073] >>>>>>>>>>>>>>>>>>> creating cluster, remoteHost, nodeID myservice,  127.0.0.1:8081, test-id 
INFO[0073] [lb_endpoints:{endpoint:{address:{socket_address:{address:"127.0.0.1"  port_value:8081}}}}] 
INFO[0073] >>>>>>>>>>>>>>>>>>> creating snapshot Version 2 
INFO[0073] OnStreamResponse...                           <<<<<<<<<<<<<<<<<<<<<<<<<<<<
INFO[0073] cb.Report()  callbacks                        fetches=0 requests=2
INFO[0073] OnStreamRequest type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment 
INFO[0073] OnStreamRequest ResourceNames [myservice] 
```

**Comment by shivamnarula** [comment]
My current envoy version:
`envoy  version: c7e8e7356d3a969c1b8e4e1f2687699acd91c6a1/1.26.1/Distribution/RELEASE/BoringSSL`

does it really depend on Envoy version?
